### ISSUE TITLE
Doesn't work with Emmet

### ISSUE THREAD

**Issue by darylknight** [fruitstudios/Craft-Twig#4]
I've just realised that this package is stopping my Emmet HTML expansions working in files using the `Craft (Twig)` syntax. For example, typing `.container` then pressing tab doesn't do anything when the syntax is `Craft (Twig)`, but it works when it's `HTML`. Any ideas?

**Comment by shornuk** [comment]
Not used Emmet at all so will have to take a look. If it's possible I'll try and add support, but very busy so it might take a while.

**Comment by mikeebee** [comment]
+1 on support for this please. This breaks all html completion, even standard stuff like closing tags.

**Comment by johanneslamers** [comment]
Same problem for me.

**Comment by darylknight** [comment]
Why has this been closed? Is it fixed?

**Comment by shornuk** [comment]
Closed as we won't be adding support ourselves. Never used Emmet so will be too time consuming to look into and test/fix. More than happy for someone to provide a fix and make a pull request, we'll add it in.

**Comment by mikeebee** [comment]
Hey everyone! I had another look into this and it turns out that you can still use the default Emmet keyboard shortcut <kbd>CTRL</kbd> + <kbd>e</kbd> to expand abbreviations while using this package.

This seems to work on most/all syntax packages that use tab to expand their own abbreviations.

Happy days :)
